document.getElementById('yesButton').addEventListener('click', generateStatement);
document.getElementById('noButton').addEventListener('click', () => {
    document.getElementById('stat').textContent = "I am glad you are strong and happy :)";
});

const statements = [
    "to make your parents proud",
            "to conquer your fears",
            "to see your family again",
            "to see your Favorite artist live",
            "to listen to music again",
            "to experience a new culture",
            "to make new friends",
            "to inspire",
            "to have your own children",
            "to adopt your own pet",
            "to make yourself proud",
            "to meet your idols",
            "to laugh until you cry",
            "to feel tears of happiness",
            "to eat your favorite food",
            "to see your siblings grow",
            "to pass school",
            "to get tattoo",
            "to smile until your cheeks hurt",
            "to meet your internet friends",
            "to find someone who loves you like you deserve",
            "to eat ice cream on a hot day",
            "to drink hot chocolate on a cold day",
            "to see untouched snow in the morning",
            "to see a sunset that sets the sky on fire",
            "to see stars light up the sky",
            "to read a book that changes your life",
            "to see the flowers in the spring",
            "to see the leaves change from green to brown",
            "to travel abroad",
            "to learn a new language",
            "to learn to draw",
            "to tell others your story in the hopes of helping them",
            "For Puppy kisses",
            "For Baby kisses (the open mouthed kind when they smack their lips on your cheek)",
            "Swear words and the release you feel when you say them",
            "Trampolines.",
            "To eat Ice cream.",
            "For Stargazing.",
            "For Cloud watching.",
            "Taking a shower and then sleeping in clean sheets.",
            "Receiving thoughtful gifts.",
            "I saw this and thought of you.",
            "The feeling you get when someone you love says, “I love you.",
            "The relief you feel after crying.",
            "Sunshine.",
            "The feeling you get when someone is listening to you/giving you their full attention.",
            "Your future wedding.",
            "Your favorite candy bar.",
            "New clothes.",
            "Witty puns.",
            "Really good bread.",
            "Holding your child in your arms for the first time.",
            "Completing a milestone (aka going to college, graduating college, getting married, getting your dream job.)",
            "The kind of dreams where you wake up and can’t stop smiling.",
            "The smell before and after it rains",
            "The sound of rain against a rooftop.",
            "The feeling you get when you’re dancing.",
            "The person (or people) that mean the most to you. Stay alive for them.",
            "Trying out new recipes.",
            "The feeling you get when your favorite song comes on the radio.",
            "The rush you get when you step onto a stage.",
            "You have to share your voice and talents and knowledge with the world because they are so valuable.",
            "To have Breakfast in bed.",
            "For Getting a middle seat in the movie theater.",
            "Breakfast for dinner (because it’s so much better at night than in the morning).",
            "Pray (if you are religious) ",
            "Forgiveness.",
            "To have Water balloon fights.",
            "To read New books by your favorite authors.",
            "To watch Fireflies.",
            "To Celebrate Birthdays.",
            "For Realizing that someone loves you.",
            "For Spending the day with someone like you.",
            "To have an Opportunity to create meaningful and lasting relationships.",
            "To be Potential to learn, grow, and evolve as a person.",
            "To get Joy and happiness in the little things.",
            "To have the power to inspire others.",
            "To have the ability to create art, music, and other forms of self-expression.",
            "To explore different cultures, traditions, and ways of life.",
            "To make a positive impact on the environment and help protect the planet.",
            "To Experience the joys of parenthood and raise a family.",
            "To Learn new things and develop new skills.",
            "To Create a legacy that will outlive you.",
            "For Being wrapped up in a warm bed.",
            "For Cuddles",
            "For Holding hands.",
            "To feel the kind of hugs when you can feel a weight being lifted off your shoulders. The kind of hug where your breath syncs with the other person’s, and you feel like the only two people in the world.",
            "For Singing off key with your best friends.",
            "To experience Road trips.",
            "For Spontaneous adventures.",
            "To Experience The feeling of sand beneath your toes.",
            "To experience the feeling when the first ocean wave rolls up and envelops your toes and ankles and knees.",
            "To see Thunderstorms.",
            "To make Your first (or hundredth) trip to Disneyland.",
            "To feel the taste of your favorite food.",
            "To experience The child-like feeling you get on Christmas morning.",
            "To experience The day when everything finally goes your way.",
            "To hear Compliments and praise.",
            "to look on this moment in 10 years time and realize you did it."

];

function generateStatement() {
    const randomIndex = Math.floor(Math.random() * statements.length);
    const randomStatement = statements[randomIndex];
    document.getElementById('stat').textContent = randomStatement;
}
